// public/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import "globals.css";

console.log("/fonts/GeistMonoVF.woff"); // Add this temporarily

const geistSans = localFont({
  src: require("../public/fonts/GeistVF.woff"),
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: require("../public/fonts/GeistMonoVF.woff"),
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
